Repository HeimerMachine/controla-app-back, pull requests merged in 2025-05, with the labels that each got.

#11 docs/added directory structure
  .github/ISSUE_TEMPLATE/ISSUE.yml
  .gitignore
  docker-compose.yml
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/config/config.ts
  src/entities/entities
  src/interfaces/controllers/controller
  src/interfaces/repositories/prisma/schema.prisma
  src/server.ts
  src/useCases/usecase
  tsconfig.json
Labels: enhancement

#15 Create pull_request_template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: documentation

#18 Feat/thulio/#14
  package.json
  pnpm-lock.yaml
  src/controllers/UserController.ts
  src/helpers/IDNullError.ts
  src/helpers/apiError.ts
  src/helpers/jwtPayload.ts
  src/helpers/user-errors/authorizationTokenNotFoundError.ts
  src/helpers/user-errors/emailRequiredError.ts
  src/helpers/user-errors/invalidConfirmPassword.ts
  src/helpers/user-errors/invalidEmailError.ts
  src/helpers/user-errors/invalidPasswordError.ts
  src/helpers/user-errors/invalidToken.ts
  src/helpers/user-errors/jwtSecretNotDefinedError.ts
  src/helpers/user-errors/nameRequiredError.ts
  src/helpers/user-errors/passwordNotMatchError.ts
  src/helpers/user-errors/passwordRequiredError.ts
  src/helpers/user-errors/userAlreadyExistsError.ts
  src/helpers/user-errors/userNotAuthorizedError.ts
  src/helpers/user-errors/userNotFoundError.ts
  src/middleware/authMiddleware
  src/middleware/authMiddleware.ts
  src/middleware/errorMiddleware
  src/middleware/errorMiddleware.ts
  src/repositories/UserRepository.ts
  src/routes/index.ts
  src/routes/public/UserPublicRoute.ts
  src/schemas/User.schema.ts
  src/server.ts
  src/services/RegisterUserUseCase.ts
  src/services/user/encryptPassword.ts
  src/services/user/loginService.ts
  src/services/user/registerService.ts
  tsconfig.json
Labels: enhancement, Backend
